### ISSUE TITLE
Define Background 

### ISSUE THREAD

**Issue by rijema** [rijema/SWE-2024#1]
-Languages
-Libraries
-Softwares/Tools

[🇧🇷](https://emojipedia.org/pt/bandeira-brasil) Adicionar as linguagens, bibliotecas e ferramentas que voce utilizou ate entao.

**Comment by AynaAraujo** [comment]
- Languages : Python ,Java, SQL ,C, Js, C++(em adamento/plano futuro)
 
- Softwares/Tools: 
  1)Python: Pycharm, Vscode, Django(em adamento), googlecolab
  2)Java: Eclipse
  3)SQL : MySQL
  4) C: CodeBlocks, Vscode
  5)Js : Vscode , React
 
- Libraries : Já trabalhei com várias para alguns projetos,mas nenhuma com um aprofudamento em específico, caso realmente  necessário posso citar algumas que utilizei em alguns projetos da faculdade de maior importância.

**Comment by Arthurecomp** [comment]
- Languages : Python, Java,  Js/ typescript
- Libraries:
    - fastify (framework)
    - React / NextJs

- Softwares/Tools:
   - VSCode, IntelliJ, Docker

**Comment by rafaelsantos1983** [comment]
Languages : Node.js(Js/ typescript), Java

Libraries:
    express
    mongoose
    spring (framework)
    docker 
    gcp
    banco relacional e não relacional

Softwares/Tools:
  VSCode (java e typescript), Eclipse

**Comment by Lucas-Cesar** [comment]
- Languages: Python, Java, SQL, Js/ typescript

- Softwares/Tools:
1)Python: Pycharm, Vscode, googlecolab
2)Java: Vscode, Eclipse
3)SQL : MySQL
4)Js/Ts : Vscode, Node.js(com express), React, Ionic

- Libraries: Nenhuma com aprofundamento específico, apesar de ter trabalhado com diversas bibliotecas em projetos de diferentes cadeiras.

**Comment by rijema** [comment]
**Languages**

Java
Javascript

Libraries:

Spring Framework
React

**Softwares/Tools:**

VSCode, IntelliJ, Docker, AWS, Kubernetes, Postman, DBeaver.

**Comment by joaovslins** [comment]
Languages

Java
Javascript
typescript
php

Libraries:
Angular
Spring Framework
Node
YII2

Softwares/Tools:

VSCode, IntelliJ, Docker, Postman, DBeaver.

**Comment by diogodsv** [comment]
Languages: Python, Java, JavaScript, C

Softwares/tools:
1. Python: pycharm, vscode, Google collab
2. Java: eclipse, vscode
3. Javascript: vscode, react
4. C: codeblocks, vscode

Libraries: nenhuma com aprofundamento específico, mas já trabalhei com muitas em diferentes projetos em variadas cadeiras
