### ISSUE TITLE
Define Synchronous time

### ISSUE THREAD

**Issue by rijema** [rijema/SWE-2024#2]
Share available periods of time through the week for you to schedule a weekly meeting.

[🇧🇷](https://emojipedia.org/pt/bandeira-brasil) Compartilhe horarios que voce esta disponivel para fazermos uma reuniao semanal sincrona online.

Ex: 21:00h Terca | 09 PM BRT Tuesday

**Comment by AynaAraujo** [comment]
Terça - 16h - 18h
Quarta - 16h - 18h
Quinta - 16h - 18h

**Comment by Arthurecomp** [comment]
18:00 Segunda-feira | 06:00 PM BRT Monday
18:00 Terça-feira | 06:00 PM BRT Tuesday
18:00 Quarta-feira | 06:00 PM BRT Wednesday
18:00 Quinta-feira | 06:00 PM BRT Thursday
18:00 Sexta-feira | 06:00 PM BRT Friday 

* Todos os dias pela parte da noite

**Comment by rafaelsantos1983** [comment]
19:30h Terca | 08 PM BRT Tuesday
19:30h Sexta | 08 PM BRT Friday

**Comment by rijema** [comment]
[20:00-22:00] Terça-feira | [08:00-10:00] PM BRT Tuesday
[20:00-22:00] Quarta-feira | [08:00-10:00] PM BRT Wednesday
[21:00-23:00] Quinta-feira | [09:00-11:00] PM BRT Thursday

**Comment by diogodsv** [comment]
20:00h Segunda | 08 PM BRT Monday
20:00h Terça | 08 PM BRT Tuesday
21:00h Quarta | 09 PM BRT Wednesday
20:00h Quinta | 08 PM BRT Thursday

**Comment by Andrealgs** [comment]
Meus horários livres são:

Segunda - 18:00 às 22:00
Terça - 18:00 às 22:00
Sexta - 18:00 às 22:00
Sábado - a combinar

**Comment by Lucas-Cesar** [comment]
Segunda à Quinta - a partir de 18h | 06 PM BRT

**Comment by joaovslins** [comment]
Segunda à sexta - das 19h às 22h
