### ISSUE TITLE
Submit here projects scenarios w/ possible stakeholders

### ISSUE THREAD

**Issue by rijema** [rijema/SWE-2024#4]
[🇧🇷](https://emojipedia.org/pt/bandeira-brasil) Envie aqui cenários de projetos com possíveis detalhes. Citar stakeholders, problema, possível solução e necessidade de prioridade. É preciso ter em mente e discutido com o mesmo stakeholder que a entrega, no momento, será um MVP.

**Comment by AynaAraujo** [comment]
Ao entrar em contato com pessoas do ramo cultural e principalmente se baseando na necessidade da professora Lana da FCAP chegamos a idea de criar uma ferramenta de mapeamento cultural  onde se coletaria,acompanharia  e analisaria os dados e impactos dos eventos culturais realizados por órgãos e equipamentos culturais.
